services:
  postgres:
    image: postgres:16-alpine
    container_name: loan-api-postgres
    environment:
      POSTGRES_DB: loan_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - loan_api_pg_data:/var/lib/postgresql/data

volumes:
  loan_api_pg_data:
